runner: mamba_ssm_lm
model_id: state-spaces/transformerpp-2.7b
tokenizer_id: EleutherAI/gpt-neox-20b
label: Transformer++ 2.7B State Spaces
revision: 15a431b71c40c284138c379d07d4008a28fea397
tokenizer_revision: c292233c833e336628618a88a648727eb3dff0a7
dtype: bfloat16
device: cuda
max_new_tokens: 8
top_k: 1
top_p: 0.0
min_p: 0.0
temperature: 1.0
