runner: hazyresearch_lm
architecture: attention
model_id: hazyresearch/attn-360m
tokenizer_id: gpt2
label: Attention 360M HazyResearch
revision: d29c38ab09b321b24a588d089053cbbe8a447b2f
dtype: bfloat16
device: cuda
max_new_tokens: 8
config_patch:
  fused_bias_fc: false
  fused_dropout_add_ln: false
